---
object_type: method
version: 1.0
object:
  attributes:
    name: start_vm
    display_name: StartVM
    description: 
    scope: instance
    language: ruby
    location: inline
    embedded_methods:
    - "/StdLib/Core/Core"
    options: {}
  inputs: []
